version: '3.7'

services:
  api:
    container_name: api
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    command: npm run start:core

  redis:
    container_name: redis
    image: redis:6
    restart: always
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
